# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
ENV LANG C.UTF-8
ENV TZ Asia/Shanghai
# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
