# https://github.com/elastic/logstash-docker
FROM docker.elastic.co/logstash/logstash-oss:6.2.4
ENV LANG C.UTF-8
ENV TZ Asia/Shanghai
# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
